name: Deploy pages
on:
  push:
    paths:
      - 'lt/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: cd lt; npm install
      - name: Build
        run: cd lt; npm run build
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: lt/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
